name: astroasix-erp
region: nyc

databases:
  - name: db
    engine: PG
    version: "15"

services:
  - name: backend
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8004
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: PORT
        scope: RUN_TIME
        value: "8004"
    
    routes:
      - path: /api

static_sites:
  - name: frontend
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: build
    
    envs:
      - key: NODE_ENV
        scope: BUILD_TIME
        value: "production"
    
    routes:
      - path: /
    
    catchall_document: index.html
